local levels = {}
local fruits = require("fruits")
local maze = require("maze")

local function getCurrentMaze()
    if not g.currentMaze then g.currentMaze = g.config.maze end
    return maze.getMaze(g.currentMaze)
end

local function getDefaultColor()
    if g.config.plusMode then return 5 else return getCurrentMaze().defaultColor end
end

local levels = {
    normal = {
        [1] = {
            pacSpeed = .8,
            pacFrightenedSpeed = .9,
            tunnelSpeed = .4,
            ghostSpeed = .75,
            frightened = 6 * 60,
            frightenedSpeed = .5,
            elroy1 = 20,
            elroy1Speed = .8,
            elroy2 = 10,
            elroy2Speed = .85,
            switch = {7*60, 27*60, 34*60, 54*60, 59*60, 79*60, 84*50},
            fruit = fruits.cherry,
            levelDisplay = { fruits.cherry },
            starvation = 4 * 60,
            pinkyCounter = 0,
            inkyCounter = 30,
            clydeCounter = 60,
        },
        [2] = {
            pacSpeed = .9,
            pacFrightenedSpeed = .95,
            tunnelSpeed = .45,
            ghostSpeed = .85,
            frightened = 5 * 60,
            frightenedSpeed = .55,
            elroy1 = 30,
            elroy1Speed = .9,
            elroy2 = 15,
            elroy2Speed = .95,
            switch = {7*60, 27*60, 34*60, 54*60, 59*60, 65520, 65521},
            fruit = fruits.strawberry,
            levelDisplay = { fruits.cherry, fruits.strawberry },
            starvation = 4 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 50,
        },
        [3] = {
            pacSpeed = .9,
            pacFrightenedSpeed = .95,
            tunnelSpeed = .45,
            ghostSpeed = .85,
            frightened = 4 * 60,
            frightenedSpeed = .55,
            elroy1 = 40,
            elroy1Speed = .9,
            elroy2 = 20,
            elroy2Speed = .95,
            switch = {7*60, 27*60, 34*60, 54*60, 59*60, 65520, 65521},
            fruit = fruits.peach,
            levelDisplay = { fruits.cherry, fruits.strawberry, fruits.peach },
            starvation = 4 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 0,
        },
        [4] = {
            pacSpeed = .9,
            pacFrightenedSpeed = .95,
            tunnelSpeed = .45,
            ghostSpeed = .85,
            frightened = 3 * 60,
            frightenedSpeed = .55,
            elroy1 = 40,
            elroy1Speed = .9,
            elroy2 = 20,
            elroy2Speed = .95,
            switch = {7*60, 27*60, 34*60, 54*60, 59*60, 65520, 65521},
            fruit = fruits.peach,
            levelDisplay = { fruits.cherry, fruits.strawberry, fruits.peach, fruits.peach },
            starvation = 4 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 0,
        },
        [5] = {
            pacSpeed = 1,
            pacFrightenedSpeed = 1,
            tunnelSpeed = .5,
            ghostSpeed = .95,
            frightened = 2 * 60,
            frightenedSpeed = .6,
            elroy1 = 40,
            elroy1Speed = 1,
            elroy2 = 20,
            elroy2Speed = 1.05,
            switch = {5*60, 25*60, 30*60, 50*60, 55*60, 65520, 65521},
            fruit = fruits.apple,
            levelDisplay = { fruits.cherry, fruits.strawberry, fruits.peach, fruits.peach, fruits.apple },
            starvation = 3 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 0,
        },
        [6] = {
            pacSpeed = 1,
            pacFrightenedSpeed = 1,
            tunnelSpeed = .5,
            ghostSpeed = .95,
            frightened = 5 * 60,
            frightenedSpeed = .6,
            elroy1 = 50,
            elroy1Speed = 1,
            elroy2 = 25,
            elroy2Speed = 1.05,
            switch = {5*60, 25*60, 30*60, 50*60, 55*60, 65520, 65521},
            fruit = fruits.apple,
            levelDisplay = { fruits.cherry, fruits.strawberry, fruits.peach, fruits.peach, fruits.apple, fruits.apple },
            starvation = 3 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 0,
        },
        [7] = {
            pacSpeed = 1,
            pacFrightenedSpeed = 1,
            tunnelSpeed = .5,
            ghostSpeed = .95,
            frightened = 2 * 60,
            frightenedSpeed = .6,
            elroy1 = 50,
            elroy1Speed = 1,
            elroy2 = 25,
            elroy2Speed = 1.05,
            switch = {5*60, 25*60, 30*60, 50*60, 55*60, 65520, 65521},
            fruit = fruits.melon,
            levelDisplay = { fruits.cherry, fruits.strawberry, fruits.peach, fruits.peach, fruits.apple, fruits.apple, fruits.melon },
            starvation = 3 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 0,
        },
        [8] = {
            pacSpeed = 1,
            pacFrightenedSpeed = 1,
            tunnelSpeed = .5,
            ghostSpeed = .95,
            frightened = 2 * 60,
            frightenedSpeed = .6,
            elroy1 = 50,
            elroy1Speed = 1,
            elroy2 = 25,
            elroy2Speed = 1.05,
            switch = {5*60, 25*60, 30*60, 50*60, 55*60, 65520, 65521},
            fruit = fruits.melon,
            levelDisplay = { fruits.strawberry, fruits.peach, fruits.peach, fruits.apple, fruits.apple, fruits.melon, fruits.melon },
            starvation = 3 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 0,
        },
        [9] = {
            pacSpeed = 1,
            pacFrightenedSpeed = 1,
            tunnelSpeed = .5,
            ghostSpeed = .95,
            frightened = 1 * 60,
            frightenedSpeed = .6,
            elroy1 = 60,
            elroy1Speed = 1,
            elroy2 = 30,
            elroy2Speed = 1.05,
            switch = {5*60, 25*60, 30*60, 50*60, 55*60, 65520, 65521},
            fruit = fruits.galaxian,
            levelDisplay = { fruits.peach, fruits.peach, fruits.apple, fruits.apple, fruits.melon, fruits.melon, fruits.galaxian },
            starvation = 3 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 0,
        },
        [10] = {
            pacSpeed = 1,
            pacFrightenedSpeed = 1,
            tunnelSpeed = .5,
            ghostSpeed = .95,
            frightened = 5 * 60,
            frightenedSpeed = .6,
            elroy1 = 60,
            elroy1Speed = 1,
            elroy2 = 30,
            elroy2Speed = 1.05,
            switch = {5*60, 25*60, 30*60, 50*60, 55*60, 65520, 65521},
            fruit = fruits.galaxian,
            levelDisplay = { fruits.peach, fruits.apple, fruits.apple, fruits.melon, fruits.melon, fruits.galaxian, fruits.galaxian },
            starvation = 3 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 0,
        },
        [11] = {
            pacSpeed = 1,
            pacFrightenedSpeed = 1,
            tunnelSpeed = .5,
            ghostSpeed = .95,
            frightened = 2 * 60,
            frightenedSpeed = .6,
            elroy1 = 60,
            elroy1Speed = 1,
            elroy2 = 30,
            elroy2Speed = 1.05,
            switch = {5*60, 25*60, 30*60, 50*60, 55*60, 65520, 65521},
            fruit = fruits.bell,
            levelDisplay = { fruits.apple, fruits.apple, fruits.melon, fruits.melon, fruits.galaxian, fruits.galaxian, fruits.bell },
            starvation = 3 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 0,
        },
        [12] = {
            pacSpeed = 1,
            pacFrightenedSpeed = 1,
            tunnelSpeed = .5,
            ghostSpeed = .95,
            frightened = 1 * 60,
            frightenedSpeed = .6,
            elroy1 = 80,
            elroy1Speed = 1,
            elroy2 = 40,
            elroy2Speed = 1.05,
            switch = {5*60, 25*60, 30*60, 50*60, 55*60, 65520, 65521},
            fruit = fruits.bell,
            levelDisplay = { fruits.apple, fruits.melon, fruits.melon, fruits.galaxian, fruits.galaxian, fruits.bell, fruits.bell },
            starvation = 3 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 0,
        },
        [13] = {
            pacSpeed = 1,
            pacFrightenedSpeed = 1,
            tunnelSpeed = .5,
            ghostSpeed = .95,
            frightened = 1 * 60,
            frightenedSpeed = .6,
            elroy1 = 80,
            elroy1Speed = 1,
            elroy2 = 40,
            elroy2Speed = 1.05,
            switch = {5*60, 25*60, 30*60, 50*60, 55*60, 65520, 65521},
            fruit = fruits.key,
            levelDisplay = { fruits.melon, fruits.melon, fruits.galaxian, fruits.galaxian, fruits.bell, fruits.bell, fruits.key },
            starvation = 3 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 0,
        },
        [14] = {
            pacSpeed = 1,
            pacFrightenedSpeed = 1,
            tunnelSpeed = .5,
            ghostSpeed = .95,
            frightened = 3 * 60,
            frightenedSpeed = .6,
            elroy1 = 80,
            elroy1Speed = 1,
            elroy2 = 40,
            elroy2Speed = 1.05,
            switch = {5*60, 25*60, 30*60, 50*60, 55*60, 65520, 65521},
            fruit = fruits.key,
            levelDisplay = { fruits.melon, fruits.galaxian, fruits.galaxian, fruits.bell, fruits.bell, fruits.key, fruits.key },
            starvation = 3 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 0,
        },
        [15] = {
            pacSpeed = 1,
            pacFrightenedSpeed = 1,
            tunnelSpeed = .5,
            ghostSpeed = .95,
            frightened = 1 * 60,
            frightenedSpeed = .6,
            elroy1 = 100,
            elroy1Speed = 1,
            elroy2 = 50,
            elroy2Speed = 1.05,
            switch = {5*60, 25*60, 30*60, 50*60, 55*60, 65520, 65521},
            fruit = fruits.key,
            levelDisplay = { fruits.galaxian, fruits.galaxian, fruits.bell, fruits.bell, fruits.key, fruits.key, fruits.key },
            starvation = 3 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 0,
        },
        [16] = {
            pacSpeed = 1,
            pacFrightenedSpeed = 1,
            tunnelSpeed = .5,
            ghostSpeed = .95,
            frightened = 1 * 60,
            frightenedSpeed = .6,
            elroy1 = 100,
            elroy1Speed = 1,
            elroy2 = 50,
            elroy2Speed = 1.05,
            switch = {5*60, 25*60, 30*60, 50*60, 55*60, 65520, 65521},
            fruit = fruits.key,
            levelDisplay = { fruits.galaxian, fruits.bell, fruits.bell, fruits.key, fruits.key, fruits.key, fruits.key },
            starvation = 3 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 0,
        },
        [17] = {
            pacSpeed = 1,
            pacFrightenedSpeed = 1,
            tunnelSpeed = .5,
            ghostSpeed = .95,
            frightened = 0 * 60,
            frightenedSpeed = .6,
            elroy1 = 100,
            elroy1Speed = 1,
            elroy2 = 50,
            elroy2Speed = 1.05,
            switch = {5*60, 25*60, 30*60, 50*60, 55*60, 65520, 65521},
            fruit = fruits.key,
            levelDisplay = { fruits.bell, fruits.bell, fruits.key, fruits.key, fruits.key, fruits.key, fruits.key },
            starvation = 3 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 0,
        },
        [18] = {
            pacSpeed = 1,
            pacFrightenedSpeed = 1,
            tunnelSpeed = .5,
            ghostSpeed = .95,
            frightened = 1 * 60,
            frightenedSpeed = .6,
            elroy1 = 100,
            elroy1Speed = 1,
            elroy2 = 50,
            elroy2Speed = 1.05,
            switch = {5*60, 25*60, 30*60, 50*60, 55*60, 65520, 65521},
            fruit = fruits.key,
            levelDisplay = { fruits.bell, fruits.key, fruits.key, fruits.key, fruits.key, fruits.key, fruits.key },
            starvation = 3 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 0,
        },
        [19] = {
            pacSpeed = 1,
            pacFrightenedSpeed = 1,
            tunnelSpeed = .5,
            ghostSpeed = .95,
            frightened = 0 * 60,
            frightenedSpeed = .6,
            elroy1 = 120,
            elroy1Speed = 1,
            elroy2 = 60,
            elroy2Speed = 1.05,
            switch = {5*60, 25*60, 30*60, 50*60, 55*60, 65520, 65521},
            fruit = fruits.key,
            levelDisplay = { fruits.key, fruits.key, fruits.key, fruits.key, fruits.key, fruits.key, fruits.key },
            starvation = 3 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 0,
        },
        [20] = {
            pacSpeed = 1,
            pacFrightenedSpeed = 1,
            tunnelSpeed = .5,
            ghostSpeed = .95,
            frightened = 0 * 60,
            frightenedSpeed = .6,
            elroy1 = 120,
            elroy1Speed = 1,
            elroy2 = 60,
            elroy2Speed = 1.05,
            switch = {5*60, 25*60, 30*60, 50*60, 55*60, 65520, 65521},
            fruit = fruits.key,
            levelDisplay = { fruits.key, fruits.key, fruits.key, fruits.key, fruits.key, fruits.key, fruits.key },
            starvation = 3 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 0,
        },
        [21] = {
            pacSpeed = .9,
            pacFrightenedSpeed = 1,
            tunnelSpeed = .5,
            ghostSpeed = .95,
            frightened = 0 * 60,
            frightenedSpeed = .6,
            elroy1 = 120,
            elroy1Speed = 1,
            elroy2 = 60,
            elroy2Speed = 1.05,
            switch = {5*60, 25*60, 30*60, 50*60, 55*60, 65520, 65521},
            fruit = fruits.key,
            levelDisplay = { fruits.key, fruits.key, fruits.key, fruits.key, fruits.key, fruits.key, fruits.key },
            starvation = 3 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 0,
        },
    },
    hard = {
        [1] = {
            pacSpeed = .9,
            pacFrightenedSpeed = .95,
            tunnelSpeed = .45,
            ghostSpeed = .85,
            frightened = 5 * 60,
            frightenedSpeed = .55,
            elroy1 = 30,
            elroy1Speed = .9,
            elroy2 = 15,
            elroy2Speed = .95,
            switch = {7*60, 27*60, 34*60, 54*60, 59*60, 65520, 65521},
            fruit = fruits.cherry,
            levelDisplay = { fruits.cherry },
            starvation = 4 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 50,
        },
        [2] = {
            pacSpeed = .9,
            pacFrightenedSpeed = .95,
            tunnelSpeed = .45,
            ghostSpeed = .85,
            frightened = 3 * 60,
            frightenedSpeed = .55,
            elroy1 = 40,
            elroy1Speed = .9,
            elroy2 = 20,
            elroy2Speed = .95,
            switch = {7*60, 27*60, 34*60, 54*60, 59*60, 65520, 65521},
            fruit = fruits.strawberry,
            levelDisplay = { fruits.cherry, fruits.strawberry },
            starvation = 4 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 0,
        },
        [3] = {
            pacSpeed = 1,
            pacFrightenedSpeed = 1,
            tunnelSpeed = .5,
            ghostSpeed = .95,
            frightened = 2 * 60,
            frightenedSpeed = .6,
            elroy1 = 40,
            elroy1Speed = 1,
            elroy2 = 20,
            elroy2Speed = 1.05,
            switch = {5*60, 25*60, 30*60, 50*60, 55*60, 65520, 65521},
            fruit = fruits.peach,
            levelDisplay = { fruits.cherry, fruits.strawberry, fruits.peach },
            starvation = 3 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 0,
        },
        [4] = {
            pacSpeed = 1,
            pacFrightenedSpeed = 1,
            tunnelSpeed = .5,
            ghostSpeed = .95,
            frightened = 2 * 60,
            frightenedSpeed = .6,
            elroy1 = 50,
            elroy1Speed = 1,
            elroy2 = 25,
            elroy2Speed = 1.05,
            switch = {5*60, 25*60, 30*60, 50*60, 55*60, 65520, 65521},
            fruit = fruits.peach,
            levelDisplay = { fruits.cherry, fruits.strawberry, fruits.peach, fruits.peach },
            starvation = 3 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 0,
        },
        [5] = {
            pacSpeed = 1,
            pacFrightenedSpeed = 1,
            tunnelSpeed = .5,
            ghostSpeed = .95,
            frightened = 2 * 60,
            frightenedSpeed = .6,
            elroy1 = 50,
            elroy1Speed = 1,
            elroy2 = 25,
            elroy2Speed = 1.05,
            switch = {5*60, 25*60, 30*60, 50*60, 55*60, 65520, 65521},
            fruit = fruits.apple,
            levelDisplay = { fruits.cherry, fruits.strawberry, fruits.peach, fruits.peach, fruits.apple },
            starvation = 3 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 0,
        },
        [6] = {
            pacSpeed = 1,
            pacFrightenedSpeed = 1,
            tunnelSpeed = .5,
            ghostSpeed = .95,
            frightened = 1 * 60,
            frightenedSpeed = .6,
            elroy1 = 60,
            elroy1Speed = 1,
            elroy2 = 30,
            elroy2Speed = 1.05,
            switch = {5*60, 25*60, 30*60, 50*60, 55*60, 65520, 65521},
            fruit = fruits.apple,
            levelDisplay = { fruits.cherry, fruits.strawberry, fruits.peach, fruits.peach, fruits.apple, fruits.apple },
            starvation = 3 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 0,
        },
        [7] = {
            pacSpeed = 1,
            pacFrightenedSpeed = 1,
            tunnelSpeed = .5,
            ghostSpeed = .95,
            frightened = 5 * 60,
            frightenedSpeed = .6,
            elroy1 = 60,
            elroy1Speed = 1,
            elroy2 = 30,
            elroy2Speed = 1.05,
            switch = {5*60, 25*60, 30*60, 50*60, 55*60, 65520, 65521},
            fruit = fruits.melon,
            levelDisplay = { fruits.cherry, fruits.strawberry, fruits.peach, fruits.peach, fruits.apple, fruits.apple, fruits.melon },
            starvation = 3 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 0,
        },
        [8] = {
            pacSpeed = 1,
            pacFrightenedSpeed = 1,
            tunnelSpeed = .5,
            ghostSpeed = .95,
            frightened = 2 * 60,
            frightenedSpeed = .6,
            elroy1 = 60,
            elroy1Speed = 1,
            elroy2 = 30,
            elroy2Speed = 1.05,
            switch = {5*60, 25*60, 30*60, 50*60, 55*60, 65520, 65521},
            fruit = fruits.melon,
            levelDisplay = { fruits.strawberry, fruits.peach, fruits.peach, fruits.apple, fruits.apple, fruits.melon, fruits.melon },
            starvation = 3 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 0,
        },
        [9] = {
            pacSpeed = 1,
            pacFrightenedSpeed = 1,
            tunnelSpeed = .5,
            ghostSpeed = .95,
            frightened = 1 * 60,
            frightenedSpeed = .6,
            elroy1 = 80,
            elroy1Speed = 1,
            elroy2 = 40,
            elroy2Speed = 1.05,
            switch = {5*60, 25*60, 30*60, 50*60, 55*60, 65520, 65521},
            fruit = fruits.galaxian,
            levelDisplay = { fruits.peach, fruits.peach, fruits.apple, fruits.apple, fruits.melon, fruits.melon, fruits.galaxian },
            starvation = 3 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 0,
        },
        [10] = {
            pacSpeed = 1,
            pacFrightenedSpeed = 1,
            tunnelSpeed = .5,
            ghostSpeed = .95,
            frightened = 1 * 60,
            frightenedSpeed = .6,
            elroy1 = 80,
            elroy1Speed = 1,
            elroy2 = 40,
            elroy2Speed = 1.05,
            switch = {5*60, 25*60, 30*60, 50*60, 55*60, 65520, 65521},
            fruit = fruits.galaxian,
            levelDisplay = { fruits.peach, fruits.apple, fruits.apple, fruits.melon, fruits.melon, fruits.galaxian, fruits.galaxian },
            starvation = 3 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 0,
        },
        [11] = {
            pacSpeed = 1,
            pacFrightenedSpeed = 1,
            tunnelSpeed = .5,
            ghostSpeed = .95,
            frightened = 3 * 60,
            frightenedSpeed = .6,
            elroy1 = 80,
            elroy1Speed = 1,
            elroy2 = 40,
            elroy2Speed = 1.05,
            switch = {5*60, 25*60, 30*60, 50*60, 55*60, 65520, 65521},
            fruit = fruits.bell,
            levelDisplay = { fruits.apple, fruits.apple, fruits.melon, fruits.melon, fruits.galaxian, fruits.galaxian, fruits.bell },
            starvation = 3 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 0,
        },
        [12] = {
            pacSpeed = 1,
            pacFrightenedSpeed = 1,
            tunnelSpeed = .5,
            ghostSpeed = .95,
            frightened = 1 * 60,
            frightenedSpeed = .6,
            elroy1 = 100,
            elroy1Speed = 1,
            elroy2 = 50,
            elroy2Speed = 1.05,
            switch = {5*60, 25*60, 30*60, 50*60, 55*60, 65520, 65521},
            fruit = fruits.bell,
            levelDisplay = { fruits.apple, fruits.melon, fruits.melon, fruits.galaxian, fruits.galaxian, fruits.bell, fruits.bell },
            starvation = 3 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 0,
        },
        [13] = {
            pacSpeed = 1,
            pacFrightenedSpeed = 1,
            tunnelSpeed = .5,
            ghostSpeed = .95,
            frightened = 1 * 60,
            frightenedSpeed = .6,
            elroy1 = 100,
            elroy1Speed = 1,
            elroy2 = 50,
            elroy2Speed = 1.05,
            switch = {5*60, 25*60, 30*60, 50*60, 55*60, 65520, 65521},
            fruit = fruits.key,
            levelDisplay = { fruits.melon, fruits.melon, fruits.galaxian, fruits.galaxian, fruits.bell, fruits.bell, fruits.key },
            starvation = 3 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 0,
        },
        [14] = {
            pacSpeed = 1,
            pacFrightenedSpeed = 1,
            tunnelSpeed = .5,
            ghostSpeed = .95,
            frightened = 0 * 60,
            frightenedSpeed = .6,
            elroy1 = 100,
            elroy1Speed = 1,
            elroy2 = 50,
            elroy2Speed = 1.05,
            switch = {5*60, 25*60, 30*60, 50*60, 55*60, 65520, 65521},
            fruit = fruits.key,
            levelDisplay = { fruits.melon, fruits.galaxian, fruits.galaxian, fruits.bell, fruits.bell, fruits.key, fruits.key },
            starvation = 3 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 0,
        },
        [15] = {
            pacSpeed = 1,
            pacFrightenedSpeed = 1,
            tunnelSpeed = .5,
            ghostSpeed = .95,
            frightened = 1 * 60,
            frightenedSpeed = .6,
            elroy1 = 100,
            elroy1Speed = 1,
            elroy2 = 50,
            elroy2Speed = 1.05,
            switch = {5*60, 25*60, 30*60, 50*60, 55*60, 65520, 65521},
            fruit = fruits.key,
            levelDisplay = { fruits.galaxian, fruits.galaxian, fruits.bell, fruits.bell, fruits.key, fruits.key, fruits.key },
            starvation = 3 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 0,
        },
        [16] = {
            pacSpeed = .9,
            pacFrightenedSpeed = 1,
            tunnelSpeed = .5,
            ghostSpeed = .95,
            frightened = 0 * 60,
            frightenedSpeed = .6,
            elroy1 = 120,
            elroy1Speed = 1,
            elroy2 = 60,
            elroy2Speed = 1.05,
            switch = {5*60, 25*60, 30*60, 50*60, 55*60, 65520, 65521},
            fruit = fruits.key,
            levelDisplay = { fruits.galaxian, fruits.bell, fruits.bell, fruits.key, fruits.key, fruits.key, fruits.key },
            starvation = 3 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 0,
        },
        [17] = {
            pacSpeed = .9,
            pacFrightenedSpeed = 1,
            tunnelSpeed = .5,
            ghostSpeed = .95,
            frightened = 0 * 60,
            frightenedSpeed = .6,
            elroy1 = 120,
            elroy1Speed = 1,
            elroy2 = 60,
            elroy2Speed = 1.05,
            switch = {5*60, 25*60, 30*60, 50*60, 55*60, 65520, 65521},
            fruit = fruits.key,
            levelDisplay = { fruits.bell, fruits.bell, fruits.key, fruits.key, fruits.key, fruits.key, fruits.key },
            starvation = 3 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 0,
        },
        [18] = {
            pacSpeed = .9,
            pacFrightenedSpeed = 1,
            tunnelSpeed = .5,
            ghostSpeed = .95,
            frightened = 0 * 60,
            frightenedSpeed = .6,
            elroy1 = 120,
            elroy1Speed = 1,
            elroy2 = 60,
            elroy2Speed = 1.05,
            switch = {5*60, 25*60, 30*60, 50*60, 55*60, 65520, 65521},
            fruit = fruits.key,
            levelDisplay = { fruits.bell, fruits.key, fruits.key, fruits.key, fruits.key, fruits.key, fruits.key },
            starvation = 3 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 0,
        },
        [19] = {
            pacSpeed = .9,
            pacFrightenedSpeed = 1,
            tunnelSpeed = .5,
            ghostSpeed = .95,
            frightened = 0 * 60,
            frightenedSpeed = .6,
            elroy1 = 120,
            elroy1Speed = 1,
            elroy2 = 60,
            elroy2Speed = 1.05,
            switch = {5*60, 25*60, 30*60, 50*60, 55*60, 65520, 65521},
            fruit = fruits.key,
            levelDisplay = { fruits.key, fruits.key, fruits.key, fruits.key, fruits.key, fruits.key, fruits.key },
            starvation = 3 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 0,
        },
    },
    plus = {
        [1] = {
            pacSpeed = 1,
            pacFrightenedSpeed = 1,
            tunnelSpeed = .5,
            ghostSpeed = .95,
            frightened = 4 * 60,
            frightenedSpeed = .5,
            elroy1 = 40,
            elroy1Speed = 1,
            elroy2 = 20,
            elroy2Speed = 1.05,
            switch = {5*60, 25*60, 30*60, 50*60, 55*60, 65520, 65521},
            fruit = fruits.cherry,
            levelDisplay = { fruits.cherry },
            starvation = 3 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 60,
        },
        [2] = {
            pacSpeed = 1,
            pacFrightenedSpeed = 1,
            tunnelSpeed = .5,
            ghostSpeed = .95,
            frightened = 3 * 60,
            frightenedSpeed = .55,
            elroy1 = 40,
            elroy1Speed = 1,
            elroy2 = 20,
            elroy2Speed = 1.05,
            switch = {5*60, 25*60, 30*60, 50*60, 55*60, 65520, 65521},
            fruit = fruits.strawberry,
            levelDisplay = { fruits.cherry, fruits.strawberry },
            starvation = 3 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 50,
        },
        [3] = {
            pacSpeed = 1,
            pacFrightenedSpeed = 1,
            tunnelSpeed = .5,
            ghostSpeed = .95,
            frightened = 2 * 60,
            frightenedSpeed = .55,
            elroy1 = 40,
            elroy1Speed = 1,
            elroy2 = 20,
            elroy2Speed = 1.05,
            switch = {5*60, 25*60, 30*60, 50*60, 55*60, 65520, 65521},
            fruit = fruits.peach,
            levelDisplay = { fruits.cherry, fruits.strawberry, fruits.peach },
            starvation = 3 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 0,
        },
        [4] = {
            pacSpeed = 1,
            pacFrightenedSpeed = 1,
            tunnelSpeed = .5,
            ghostSpeed = .95,
            frightened = 1 * 60,
            frightenedSpeed = .55,
            elroy1 = 40,
            elroy1Speed = 1,
            elroy2 = 20,
            elroy2Speed = 1.05,
            switch = {5*60, 25*60, 30*60, 50*60, 55*60, 65520, 65521},
            fruit = fruits.peach,
            levelDisplay = { fruits.cherry, fruits.strawberry, fruits.peach, fruits.peach },
            starvation = 3 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 0,
        },
        [5] = {
            pacSpeed = 1,
            pacFrightenedSpeed = 1,
            tunnelSpeed = .5,
            ghostSpeed = .95,
            frightened = 2 * 60,
            frightenedSpeed = .6,
            elroy1 = 40,
            elroy1Speed = 1,
            elroy2 = 20,
            elroy2Speed = 1.05,
            switch = {5*60, 25*60, 30*60, 50*60, 55*60, 65520, 65521},
            fruit = fruits.apple,
            levelDisplay = { fruits.cherry, fruits.strawberry, fruits.peach, fruits.peach, fruits.apple },
            starvation = 3 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 0,
        },
        [6] = {
            pacSpeed = 1,
            pacFrightenedSpeed = 1,
            tunnelSpeed = .5,
            ghostSpeed = .95,
            frightened = 5 * 60,
            frightenedSpeed = .6,
            elroy1 = 50,
            elroy1Speed = 1,
            elroy2 = 25,
            elroy2Speed = 1.05,
            switch = {5*60, 25*60, 30*60, 50*60, 55*60, 65520, 65521},
            fruit = fruits.apple,
            levelDisplay = { fruits.cherry, fruits.strawberry, fruits.peach, fruits.peach, fruits.apple, fruits.apple },
            starvation = 3 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 0,
        },
        [7] = {
            pacSpeed = 1,
            pacFrightenedSpeed = 1,
            tunnelSpeed = .5,
            ghostSpeed = .95,
            frightened = 2 * 60,
            frightenedSpeed = .6,
            elroy1 = 50,
            elroy1Speed = 1,
            elroy2 = 25,
            elroy2Speed = 1.05,
            switch = {5*60, 25*60, 30*60, 50*60, 55*60, 65520, 65521},
            fruit = fruits.melon,
            levelDisplay = { fruits.cherry, fruits.strawberry, fruits.peach, fruits.peach, fruits.apple, fruits.apple, fruits.melon },
            starvation = 3 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 0,
        },
        [8] = {
            pacSpeed = 1,
            pacFrightenedSpeed = 1,
            tunnelSpeed = .5,
            ghostSpeed = .95,
            frightened = 2 * 60,
            frightenedSpeed = .6,
            elroy1 = 50,
            elroy1Speed = 1,
            elroy2 = 25,
            elroy2Speed = 1.05,
            switch = {5*60, 25*60, 30*60, 50*60, 55*60, 65520, 65521},
            fruit = fruits.melon,
            levelDisplay = { fruits.strawberry, fruits.peach, fruits.peach, fruits.apple, fruits.apple, fruits.melon, fruits.melon },
            starvation = 3 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 0,
        },
        [9] = {
            pacSpeed = 1,
            pacFrightenedSpeed = 1,
            tunnelSpeed = .5,
            ghostSpeed = .95,
            frightened = 1 * 60,
            frightenedSpeed = .6,
            elroy1 = 60,
            elroy1Speed = 1,
            elroy2 = 30,
            elroy2Speed = 1.05,
            switch = {5*60, 25*60, 30*60, 50*60, 55*60, 65520, 65521},
            fruit = fruits.galaxian,
            levelDisplay = { fruits.peach, fruits.peach, fruits.apple, fruits.apple, fruits.melon, fruits.melon, fruits.galaxian },
            starvation = 3 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 0,
        },
        [10] = {
            pacSpeed = 1,
            pacFrightenedSpeed = 1,
            tunnelSpeed = .5,
            ghostSpeed = .95,
            frightened = 5 * 60,
            frightenedSpeed = .6,
            elroy1 = 60,
            elroy1Speed = 1,
            elroy2 = 30,
            elroy2Speed = 1.05,
            switch = {5*60, 25*60, 30*60, 50*60, 55*60, 65520, 65521},
            fruit = fruits.galaxian,
            levelDisplay = { fruits.peach, fruits.apple, fruits.apple, fruits.melon, fruits.melon, fruits.galaxian, fruits.galaxian },
            starvation = 3 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 0,
        },
        [11] = {
            pacSpeed = 1,
            pacFrightenedSpeed = 1,
            tunnelSpeed = .5,
            ghostSpeed = .95,
            frightened = 2 * 60,
            frightenedSpeed = .6,
            elroy1 = 60,
            elroy1Speed = 1,
            elroy2 = 30,
            elroy2Speed = 1.05,
            switch = {5*60, 25*60, 30*60, 50*60, 55*60, 65520, 65521},
            fruit = fruits.bell,
            levelDisplay = { fruits.apple, fruits.apple, fruits.melon, fruits.melon, fruits.galaxian, fruits.galaxian, fruits.bell },
            starvation = 3 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 0,
        },
        [12] = {
            pacSpeed = 1,
            pacFrightenedSpeed = 1,
            tunnelSpeed = .5,
            ghostSpeed = .95,
            frightened = 1 * 60,
            frightenedSpeed = .6,
            elroy1 = 80,
            elroy1Speed = 1,
            elroy2 = 40,
            elroy2Speed = 1.05,
            switch = {5*60, 25*60, 30*60, 50*60, 55*60, 65520, 65521},
            fruit = fruits.bell,
            levelDisplay = { fruits.apple, fruits.melon, fruits.melon, fruits.galaxian, fruits.galaxian, fruits.bell, fruits.bell },
            starvation = 3 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 0,
        },
        [13] = {
            pacSpeed = 1,
            pacFrightenedSpeed = 1,
            tunnelSpeed = .5,
            ghostSpeed = .95,
            frightened = 1 * 60,
            frightenedSpeed = .6,
            elroy1 = 80,
            elroy1Speed = 1,
            elroy2 = 40,
            elroy2Speed = 1.05,
            switch = {5*60, 25*60, 30*60, 50*60, 55*60, 65520, 65521},
            fruit = fruits.key,
            levelDisplay = { fruits.melon, fruits.melon, fruits.galaxian, fruits.galaxian, fruits.bell, fruits.bell, fruits.key },
            starvation = 3 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 0,
        },
        [14] = {
            pacSpeed = 1,
            pacFrightenedSpeed = 1,
            tunnelSpeed = .5,
            ghostSpeed = .95,
            frightened = 3 * 60,
            frightenedSpeed = .6,
            elroy1 = 80,
            elroy1Speed = 1,
            elroy2 = 40,
            elroy2Speed = 1.05,
            switch = {5*60, 25*60, 30*60, 50*60, 55*60, 65520, 65521},
            fruit = fruits.key,
            levelDisplay = { fruits.melon, fruits.galaxian, fruits.galaxian, fruits.bell, fruits.bell, fruits.key, fruits.key },
            starvation = 3 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 0,
        },
        [15] = {
            pacSpeed = 1,
            pacFrightenedSpeed = 1,
            tunnelSpeed = .5,
            ghostSpeed = .95,
            frightened = 1 * 60,
            frightenedSpeed = .6,
            elroy1 = 100,
            elroy1Speed = 1,
            elroy2 = 50,
            elroy2Speed = 1.05,
            switch = {5*60, 25*60, 30*60, 50*60, 55*60, 65520, 65521},
            fruit = fruits.key,
            levelDisplay = { fruits.galaxian, fruits.galaxian, fruits.bell, fruits.bell, fruits.key, fruits.key, fruits.key },
            starvation = 3 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 0,
        },
        [16] = {
            pacSpeed = 1,
            pacFrightenedSpeed = 1,
            tunnelSpeed = .5,
            ghostSpeed = .95,
            frightened = 1 * 60,
            frightenedSpeed = .6,
            elroy1 = 100,
            elroy1Speed = 1,
            elroy2 = 50,
            elroy2Speed = 1.05,
            switch = {5*60, 25*60, 30*60, 50*60, 55*60, 65520, 65521},
            fruit = fruits.key,
            levelDisplay = { fruits.galaxian, fruits.bell, fruits.bell, fruits.key, fruits.key, fruits.key, fruits.key },
            starvation = 3 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 0,
        },
        [17] = {
            pacSpeed = 1,
            pacFrightenedSpeed = 1,
            tunnelSpeed = .5,
            ghostSpeed = .95,
            frightened = 0 * 60,
            frightenedSpeed = .6,
            elroy1 = 100,
            elroy1Speed = 1,
            elroy2 = 50,
            elroy2Speed = 1.05,
            switch = {5*60, 25*60, 30*60, 50*60, 55*60, 65520, 65521},
            fruit = fruits.key,
            levelDisplay = { fruits.bell, fruits.bell, fruits.key, fruits.key, fruits.key, fruits.key, fruits.key },
            starvation = 3 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 0,
        },
        [18] = {
            pacSpeed = 1,
            pacFrightenedSpeed = 1,
            tunnelSpeed = .5,
            ghostSpeed = .95,
            frightened = 1 * 60,
            frightenedSpeed = .6,
            elroy1 = 100,
            elroy1Speed = 1,
            elroy2 = 50,
            elroy2Speed = 1.05,
            switch = {5*60, 25*60, 30*60, 50*60, 55*60, 65520, 65521},
            fruit = fruits.key,
            levelDisplay = { fruits.bell, fruits.key, fruits.key, fruits.key, fruits.key, fruits.key, fruits.key },
            starvation = 3 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 0,
        },
        [19] = {
            pacSpeed = 1,
            pacFrightenedSpeed = 1,
            tunnelSpeed = .5,
            ghostSpeed = .95,
            frightened = 0 * 60,
            frightenedSpeed = .6,
            elroy1 = 120,
            elroy1Speed = 1,
            elroy2 = 60,
            elroy2Speed = 1.05,
            switch = {5*60, 25*60, 30*60, 50*60, 55*60, 65520, 65521},
            fruit = fruits.key,
            levelDisplay = { fruits.key, fruits.key, fruits.key, fruits.key, fruits.key, fruits.key, fruits.key },
            starvation = 3 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 0,
        },
        [20] = {
            pacSpeed = 1,
            pacFrightenedSpeed = 1,
            tunnelSpeed = .5,
            ghostSpeed = .95,
            frightened = 0 * 60,
            frightenedSpeed = .6,
            elroy1 = 120,
            elroy1Speed = 1,
            elroy2 = 60,
            elroy2Speed = 1.05,
            switch = {5*60, 25*60, 30*60, 50*60, 55*60, 65520, 65521},
            fruit = fruits.key,
            levelDisplay = { fruits.key, fruits.key, fruits.key, fruits.key, fruits.key, fruits.key, fruits.key },
            starvation = 3 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 0,
        },
        [21] = {
            pacSpeed = .9,
            pacFrightenedSpeed = 1,
            tunnelSpeed = .5,
            ghostSpeed = .95,
            frightened = 0 * 60,
            frightenedSpeed = .6,
            elroy1 = 120,
            elroy1Speed = 1,
            elroy2 = 60,
            elroy2Speed = 1.05,
            switch = {5*60, 25*60, 30*60, 50*60, 55*60, 65520, 65521},
            fruit = fruits.key,
            levelDisplay = { fruits.key, fruits.key, fruits.key, fruits.key, fruits.key, fruits.key, fruits.key },
            starvation = 3 * 60,
            pinkyCounter = 0,
            inkyCounter = 0,
            clydeCounter = 0,
        },
    },
}

local plusModeFruitMap = {
    [fruits.cherry] = fruits.cola,
    [fruits.strawberry] = fruits.cocktail,
    [fruits.peach] = fruits.peas,
    [fruits.melon] = fruits.grapes,
    [fruits.bell] = fruits.bread,
    [fruits.key] = fruits.pancakes
}

-- i don't love this
local fruitFrightenedDurations = {
    [1] = 6,
    [2] = 6,
    [3] = 5,
    [4] = 5,
    [5] = 4,
    [6] = 4,
    [7] = 4,
    [8] = 3,
    [9] = 3,
    [10] = 3,
    [11] = 2,
    [12] = 2,
    [13] = 2,
    [14] = 2,
    [15] = 2,
    [16] = 2,
    [17] = 2,
    [18] = 2,
    [19] = 2,
    [20] = 2,
    [21] = 2,
}

-- Helper function to copy a level table (deep copy with shallow copy for nested tables)
local function copyLevelTable(source)
    local copy = {}
    for k, v in pairs(source) do
        if type(v) == "table" then
            -- shallow copy for tables
            copy[k] = {}
            for k2, v2 in pairs(v) do
                copy[k][k2] = v2
            end
        else
            copy[k] = v
        end
    end
    return copy
end

levels.getLevel = function(levelNumber)
    local currentLevels = g.config.difficulty == 1 and levels.hard or g.config.difficulty == 2 and levels.plus or levels.normal
    local defaultLevel = g.config.difficulty == 1 and 19 or 21
    local currentLevel

    -- I don't love this
    if currentLevels[levelNumber] then
        -- Deep copy (shallow, for the level table, since values are primitives/tables)
        currentLevel = copyLevelTable(currentLevels[levelNumber])
        currentLevel.fruitFrightenedDuration = fruitFrightenedDurations[levelNumber] * 60
    else
        -- Create a copy of the default level instead of assigning
        currentLevel = copyLevelTable(currentLevels[defaultLevel])
        currentLevel.fruitFrightenedDuration = fruitFrightenedDurations[#fruitFrightenedDurations] * 60
    end

    if g.config.plusMode then
        -- Translate fruit property if it matches any special case
        if plusModeFruitMap[currentLevel.fruit] then
            currentLevel.fruit = plusModeFruitMap[currentLevel.fruit]
        end

        -- Translate all values in levelDisplay according to the mapping
        if currentLevel.levelDisplay then
            for i, fruit in ipairs(currentLevel.levelDisplay) do
                if plusModeFruitMap[fruit] then
                    currentLevel.levelDisplay[i] = plusModeFruitMap[fruit]
                end
            end
        end
    end

    return currentLevel
end

levels.startLevel = function()
    g.level = levels.getLevel(g.levelNumber)
    g.fruitTimer = false
    g.starvation = 0
    g.level.timer = 0
    g.level.chase = g.config.scatterOption == 2 and true or false
    g.frightened = false
    g.mazeFrightened = false
    g.fruitFrightened = false
    g.globalCounter = false
    g.suspendElroy = false
    g.currentMaze = g.config.maze == "random" and g.mazes[math.random(1, #g.mazes)] or g.config.maze
    g.currentMazeColor = g.config.mazeColor == 99 and getDefaultColor() or g.config.mazeColor == 0 and math.random(1, maze.maxColors - 1) or g.config.mazeColor
    g.currentBackground = g.config.background == "random" and backgroundOptions[math.random(2, #backgroundOptions)] or g.config.background
end

levels.resetLevel = function()
    g.level = levels.getLevel(g.levelNumber)
    g.fruitTimer = false
    g.starvation = 0
    g.level.timer = 0
    g.level.chase = g.config.scatterOption == 2 and true or false
    g.frightened = false
    g.mazeFrightened = false
    g.fruitFrightened = false
end

return levels